# file: playbook-wake-on-lan.yml
---
- name: Wake On LAN Windows clients
  hosts: all
  tasks:
    - name: Send magic packet to 'lyd-office'
      wakeonlan:
        mac: '00:30:48:D3:7B:47'
      delegate_to: localhost

    - name: Send magic packet to 'upstairs-htpc'
      wakeonlan:
        mac: '84:2B:2B:AB:86:39'
      delegate_to: localhost