# file: playbook-choco-install-or-upgrade-keepass.yml
---
- name: Install or upgrade KeePass using Chocolatey
  hosts: all
  tasks:
    - name: Ensure KeePass process is not running
      win_shell: 'Stop-Process -Name "KeePass" -ErrorAction SilentlyContinue -Confirm:$false -Force'
      ignore_errors: yes
      register: stop_result

    - name: Disable Chocolatey enhanced exit codes
      win_chocolatey_feature:
        name: useEnhancedExitCodes
        state: disabled
      register: disable_result

    - name: Bring KeePass package to latest version state
      win_chocolatey:
        name: "keepass"
        state: latest
      register: package_result

    - debug:
        var: stop_result
        var: disable_result
        var: package_result