# file: playbook-vmware-start-vm.yml
---
- name: Start a virtual machine
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Start VM
      command: pwsh ~/it-scripts-vmware/Start-VirtualMachine.ps1 -User "{{ username }}" -Password "{{ password }}" -ServerAddress "{{ server }}" -DataCenterName "{{ datacenter }}" -VMName "{{ vmname }}"
      ignore_errors: yes
      changed_when: false
      register: powershell_output