# file: playbook-vmware-create-vm-from-template.yml
---
- name: Create a virtual machine from a template
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Clone VM from template
      command: pwsh ~/it-scripts-vmware/New-VirtualMachineFromTemplate.ps1 -User "{{ username }}" -Password "{{ password }}" -ServerAddress "{{ server }}" -DataCenterName "{{ datacenter }}" -ResourcePoolName "{{ pool }}" -TemplateName "{{ template }}" -VMName "{{ vmname }}" -Location "{{ location }}"
      register: powershell_output