# file: playbook-choco-install-or-upgrade-keepass.yml
---
- name: Install or upgrade KeePass using Chocolatey
  hosts: all
  tasks:
    - name: Ensure KeePass process is not running
      win_shell: 'Stop-Process -Name "KeePass" -ErrorAction SilentlyContinue -Confirm:$false -Force'
      ignore_errors: yes
      register: stop_result

    - name: Bring KeePass package to latest version state
      win_chocolatey:
        name: "keepass"
        state: latest
      register: package_result

    - name: Ensure KeePass is running (with config)
      win_command: 'net use {{ smb_share}} /user:{{ smb_user }} {{ smb_pass }} /persistent:yes'
      win_shell: '"C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe" {{ kdbx_path }} -preselect:{{ key_path }} -cfg-local:{{ config_path }}'
      args:
        executable: cmd
      register: start_result

    - debug:
        var: stop_result
        var: package_result
        var: start_result