# file: playbook-wake-on-lan.yml
---
- name: Wake On LAN Windows clients
  hosts: all
  tasks:
    - name: Send magic packet to 'lyd-office'
      command: /usr/bin/wakeonlan 00:30:48:D3:7B:47

    - name: Send magic packet to 'upstairs-htpc'
      command: /usr/bin/wakeonlan 84:2B:2B:AB:86:39

    - name: Send magic packet to 'nat-bedroom'
      command: /usr/bin/wakeonlan 48:51:B7:1C:76:1D