# file: playbook-choco-install-or-upgrade-packages.yml
---
- name: Install or upgrade a list of packages using Chocolatey
  hosts: all
  tasks:
    # Set AC 'Sleep after' setting to 'Never'
    - import_tasks: playbook-powercfg-set-sleep.yml
      vars:
        sleep_after_value: 0

    - name: Disable Chocolatey enhanced exit codes
      win_chocolatey_feature:
        name: useEnhancedExitCodes
        state: disabled
      register: disable_result
    
    - name: Bring packages list to latest version state
      win_chocolatey:
        name: "{{ packages }}"
        skip_scripts: "{{ skip_scripts }}"
        package_params: "{{ package_params }}"
        ignore_checksums: "{{ ignore_checksums }}"
        state: latest
      register: packages_result

    # Set AC 'Sleep after' setting to '30 minutes'
    - import_tasks: playbook-powercfg-set-sleep.yml
      vars:
        sleep_after_value: 1800

    - debug:
        var: disable_result
        var: packages_result
