# file: playbook-install-AhkServiceTest.yml
---
- name: testing installing a service
  hosts: all
  tasks:
    - name: Install AhkServiceTest
      win_chocolatey:
        name: ahk-service-test
        source: http://tfs/City%20of%20Davenport/_packaging/cod-nuget.release/nuget/v2
        state: latest
        allow_prerelease: yes

    - name: Create Service - AhkServiceTest
      win_nssm:
        name: ahk-service-test
        application: C:\ProgramData\chocolatey\lib\ahk-service-test\ahk-service-test.exe

    - name: Configure Service - AhkServiceTest
      win_service:
        name: ahk-service-test
        display_name: AhkServiceTest
        description: a wacky crazy service test!!!

    - name: Start Service - AhkServiceTest
      win_service:
        name: ahk-service-test
        state: started